# Observium and MariaDB container
# Maintained by somsakc@hotmail.com
# See update at https://github.com/somsakc/observium

version: '2'

services:
  observiumdb:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_DB_NAME=observium
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
       volumes:
         - /home/docker/observium/db:/var/lib/mysql
         - /home/docker/observium/mysql:/docker-entrypoint-initdb.d
       networks:
         - back-tier
       restart: always

  observiumap:
       image: somsakc/observium
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
       volumes:
         - /home/docker/observium/lock:/opt/observium/lock
       networks:
         - back-tier
       ports:
         - "80:80"
       restart: always
       depends_on:
         - observiumdb

networks:
  back-tier:
      driver: bridge

